export const loadCharacter = (id) => {
  console.log(`Load character with ID "${id}"`)

  return {
    id,
    settingId: Math.ceil(Math.random() * 50),
    name: 'Test Character',
    characteristics: {
      agility: 2,
      brawn: 2,
      cunning: 2,
      intellect: 2,
      presence: 2,
      willpower: 2,
    },
    skills: {
      alchemy: 0,
      arcana: 0,
      astrocartography: 0,
      athletics: 0,
      brawl: 0,
      charm: 0,
      coercion: 0,
      computers: 0,
      cool: 0,
      coordination: 0,
      deception: 0,
      discipline: 0,
      divine: 0,
      driving: 0,
      gunnery: 0,
      knowledge: 0,
      leadership: 0,
      mechanics: 0,
      medicine: 0,
      melee: 0,
      melee: 0,
      melee: 0,
      negotiation: 0,
      operating: 0,
      perception: 0,
      piloting: 0,
      primal: 0,
      ranged: 0,
      ranged: 0,
      ranged: 0,
      resilience: 0,
      riding: 0,
      skulduggery: 0,
      stealth: 0,
      streetwise: 0,
      survival: 0,
      vigilance: 0,
    },
    speciesId: 1,
    careerId: 1,
    talentIds: [],
    earnedXp: 0,
    spentXp: 0,
  }
}
